version: '3'

services:
    monitoring_agent:
        container_name: "monitoring_agent"
        build: .
        image: h0rzn/monitoring_agent:v0.1-beta
        ports: 
          - 8080:8080
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock